version: '3.8'

services:
  front:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    depends_on:
      - back

  back:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
