FROM python:3.8-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY fastapi-back/src/app/ .
COPY fastapi-back/src/model/ .

COPY model/mnist-0.0.1.pt /app/model/mnist-0.0.1.pt

EXPOSE 8000

CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
